apiVersion: apps/v1
kind: Deployment

metadata:
  name: mm-bre

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mm-bre

  template:
    metadata:
      labels:
        app: mm-bre

    spec:
      containers:
        - name: mm-bre
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}
